"""Build the inline icon sprite from Bootstrap Icons.

    python tools/build_icon_sprite.py

Writes ``app/templates/_icons.html``, which base.html includes once per page.

Why a sprite and not the icon font
----------------------------------
base.html used to load the Bootstrap Icons stylesheet and its web font from
jsDelivr: about 100 kB of CSS mapping 2,000 glyph names to codepoints, plus a
120 kB font file, to draw the sixty icons this app actually uses. It also meant
a third party saw the IP address of everyone who opened a health assessment,
and that a blocked CDN left the pages full of empty squares.

Sixty glyphs as SVG paths come to roughly a quarter of that, from this origin,
with no font to load and no flash of missing icons.

Why inline rather than a static .svg file
-----------------------------------------
``<use href="/static/img/icons.svg#i-heart">`` is the tidier spelling and would
be cached across pages, but Safari still refuses to resolve ``<use>`` into an
external document. On a health tool, "works everywhere" beats "saves a request".

Which icons
-----------
Discovered, not listed by hand -- the templates, the JavaScript and the concern
definitions in app/ml/triage.py are scanned for the names they reference, so an
icon added to a page cannot be silently missing from the sprite. Running this
after adding one is the whole maintenance burden, and
tests/test_design_system.py fails if the sprite and the templates disagree.

Bootstrap Icons is MIT licensed. The version is pinned below; the fetched paths
are committed, so a build never depends on the CDN being up.
"""

from __future__ import annotations

import argparse
import logging
import re
import sys
from pathlib import Path

import requests

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "app" / "templates" / "_icons.html"
VERSION = "1.11.1"

log = logging.getLogger("icons")

# Where an icon name can be written, and how to recognise one there.
SOURCES = (
    (ROOT / "app" / "templates", "*.html", re.compile(r"bi bi-([a-z0-9-]+)")),
    (ROOT / "app" / "static" / "js", "*.js", re.compile(r"bi bi-([a-z0-9-]+)")),
    (ROOT / "app" / "templates", "*.html", re.compile(r'href="#i-([a-z0-9-]+)"')),
    (ROOT / "app" / "static" / "js", "*.js", re.compile(r'href="#i-([a-z0-9-]+)"')),
    (ROOT / "app" / "ml", "*.py", re.compile(r'icon="(?:bi-)?([a-z0-9-]+)"')),
)


def discover():
    """Every icon name referenced anywhere in the app."""
    names = set()
    for directory, glob, pattern in SOURCES:
        for path in directory.glob(glob):
            names.update(pattern.findall(path.read_text(encoding="utf-8")))
    return sorted(names)


def fetch(name, session):
    """One icon's drawing instructions and its viewBox."""
    url = f"https://cdn.jsdelivr.net/npm/bootstrap-icons@{VERSION}/icons/{name}.svg"
    response = session.get(url, timeout=20)
    if response.status_code == 404:
        raise SystemExit(
            f"bootstrap-icons has no icon called {name!r}. Check the spelling "
            f"where it is referenced -- a typo here is an invisible icon, not "
            f"an error, once this sprite is built."
        )
    response.raise_for_status()

    body = re.search(r"<svg[^>]*>(.*)</svg>", response.text, re.S)
    viewbox = re.search(r'viewBox="([^"]+)"', response.text)
    if not body or not viewbox:
        raise SystemExit(f"{name}: could not parse the SVG returned for {url}")
    # Only the paths. Width, height, colour and class belong to the page that
    # draws the icon, not to the sprite.
    return re.sub(r"\s+", " ", body.group(1)).strip(), viewbox.group(1)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--version", default=VERSION)
    args = parser.parse_args(argv)

    logging.basicConfig(level=logging.INFO, format="%(message)s")
    names = discover()
    log.info("bootstrap-icons %s: %d icons referenced by the app", args.version, len(names))

    session = requests.Session()
    symbols = [
        f'<symbol id="i-{name}" viewBox="{viewbox}">{body}</symbol>'
        for name, (body, viewbox) in ((n, fetch(n, session)) for n in names)
    ]

    OUT.write_text(
        f"{{# Bootstrap Icons v{args.version} (MIT) -- only the {len(symbols)} "
        f"glyphs this app uses.\n"
        f"   Generated by tools/build_icon_sprite.py; edit that, not this.\n"
        f"   Inlined rather than served as a file because Safari does not\n"
        f"   resolve <use> into an external document. #}}\n"
        f'<svg xmlns="http://www.w3.org/2000/svg" hidden aria-hidden="true">\n  '
        + "\n  ".join(symbols)
        + "\n</svg>\n",
        encoding="utf-8",
    )
    log.info("wrote %s (%.1f kB)", OUT.relative_to(ROOT), OUT.stat().st_size / 1024)
    return names


if __name__ == "__main__":
    sys.exit(0 if main() else 1)
